### ISSUE TITLE
L2RPackReader has stopped working [Crash]

### ISSUE THREAD

**Issue by LordAzuRa** [AngryHank/Lin2RevJunk#2] opened 2018-04-16 04:19 UTC
Your Packet Reader has been an absolute time saver for me on L2R Global (US) but it has unfortunately been crashing for the last month or so, it seems an update triggered the issue.
I am running L2R through Bluestacks.

Is there any fix planned for it?
Find attached the message and state of the command prompt when the crash occurs. 

![l2rpacketcrash](https://user-images.githubusercontent.com/20749497/38790059-74a99f06-410c-11e8-81bb-21c2d460950f.png)

**Comment by AMiniLegend** [comment] 2018-05-01 15:03
I believe the fix for this was reading a single byte more, after the introduction string in PktGuildMemberListReadresult.cs. It looks like he's already fixed it though.

**Comment by LordAzuRa** [comment] 2018-05-07 01:11
I still have the same crash after grabbing the latest version :(
It happens as soon as I press Enter to stop it.

**Comment by AMiniLegend** [comment] 2018-05-07 01:24
Are you building from the source? I don't believe the one that's built is the current version, so it wouldn't have the fix in it.

**Comment by LordAzuRa** [comment] 2018-05-07 04:30
Ahhh no, I'm a noob when it comes to that. I did try and grabbed the proper VS version but when I tried to compile the project I was plagued with multiple errors that I am unable to troubleshoot.
I wish he did submit a fixed compile version :(

**Comment by AMiniLegend** [comment] 2018-05-11 14:41
It looks like he's updated the executable. If it works for you, you can probably close this issue.

**Comment by Moxer81** [comment] 2018-06-25 02:53
I have the same issue when I try to grab my clan memberlist. I get the same error:

![2018-06-25_4-50-07](https://user-images.githubusercontent.com/40553645/41828069-567cb726-7833-11e8-8f92-de4d6a4eb51d.png)

I noticed that it happens with my clan, and other clans when checking members from ranking list, while some clans members lists were completed without the error. 
Maybe something with name string lengths or something similar? Could this be solved?

**Comment by AMiniLegend** [comment] 2018-06-26 16:52
I may have had this issue earlier. If it is the same one, I added a sleep in the loop for the guild member list function, and I haven't seen the issue since.

**Comment by Moxer81** [comment] 2018-06-26 18:46
Could you elaborate how to do this? I understand you edited this on the source but actually I have no experience with it, I use the executable file in tools.

**Comment by AMiniLegend** [comment] 2018-06-26 20:57
Try adding "System.Threading.Thread.Sleep(10);" (without quotes) on line 58 of the file "PktGuildMemberListReadresult.cs" in "SourceFiles/L2RPacketReader/L2RPacketReader/L2RPacketReader/Parser/Parsers/". Then rebuild the tool.

To rebuild it you'll need Visual Studio 2017 (Community edition). You open the solution file (.sln) and go to Build->Build Solution. The output will be in the bin folder of the source location.

FWIW, I don't know if that will fix the issue for you.

**Comment by patotskiy** [comment] 2018-07-10 08:58
Can someone create PR with fix for:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at L2RPacketReader.PacketReader.ReadString()
   at L2RPacketReader.Parser.Parsers.PktChatGuildListReadResult.Packet(PacketReader packet)
   at L2RPacketReader.Parser.Handler.Parse(PacketReader packet, UInt16 packetID)
   at L2RPacketReader.RecordPackets.AppendIncomingData(Byte[] payloadData)
   at L2RPacketReader.RecordPackets.PacketCapturer(Object sender, CaptureEventArgs e)
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```



After rebuilding from sources is faced with problem:

`
PacketID: 25D   Length: 44
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Patotsky\Packets\PktSkillStartNotify(44).dat'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at L2RPacketReader.Parser.HandlerINT.TypePacket(PacketReader packet, UInt16 packetID) in C:\Users\Patotsky\Downloads\Archives\Lin2RevJunk-master\Lin2RevJunk-master\SourceFiles\L2RPacketReader\L2RPacketReader\L2RPacketReader\Parser\HandlerINT.cs:line 4990
   at L2RPacketReader.RecordPackets.ParsePacket(PacketReader packet) in C:\Users\Patotsky\Downloads\Archives\Lin2RevJunk-master\Lin2RevJunk-master\SourceFiles\L2RPacketReader\L2RPacketReader\L2RPacketReader\Program.cs:line 139
   at L2RPacketReader.RecordPackets.AppendIncomingData(Byte[] payloadData) in C:\Users\Patotsky\Downloads\Archives\Lin2RevJunk-master\Lin2RevJunk-master\SourceFiles\L2RPacketReader\L2RPacketReader\L2RPacketReader\Program.cs:line 117
   at L2RPacketReader.RecordPackets.PacketCapturer(Object sender, CaptureEventArgs e) in C:\Users\Patotsky\Downloads\Archives\Lin2RevJunk-master\Lin2RevJunk-master\SourceFiles\L2RPacketReader\L2RPacketReader\L2RPacketReader\Program.cs:line 94
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
`

**Comment by AMiniLegend** [comment] 2018-07-18 16:42
For the source error, you need to copy the "Packets" folder that's in the already-built executable's folder, into your debug/release folder in the source folder

**Comment by Moxer81** [comment] 2018-07-18 16:45
Yeah figured that out! and it works like a charm since then. Thanks alot
for your great help and sorry for the late reply

**Comment by patotskiy** [comment] 2018-07-19 11:02
@AMiniLegend Could you please point me where is "Packets" folder located?

Or I do not understand something :-) I faced with issue: Could not find a part of the path ... \L2RPacketReader\L2RPacketReader\L2RPacketReader\bin\Debug\Packets\PktNpcMoveNotify(34).dat'....

**Comment by AMiniLegend** [comment] 2018-07-19 12:44
I just looked at it again, and you don't actually need to copy anything. Just make a new folder called "Packets". I think the problem is that the folder doesn't exist, so it can't write the files correctly.

**Comment by patotskiy** [comment] 2018-07-19 13:24
@AMiniLegend Thanks!! 
And final question, how to convert dat file to csv? Previously, this was done automatically. 
Or latest source code is draft and still in development?

**Comment by AMiniLegend** [comment] 2018-07-19 13:27
The dat file is different from the csv file. The dat file contains the packet data from when you run the tool, so you don't need to make those. The csv files come from the other tool (decrypt) and from the game data, but those should already exist somewhere, so you shouldn't need to decrypt those files unless you want the latest ones.

**Comment by patotskiy** [comment] 2018-07-19 13:31
In this case I don't understand why my output folder is empty :)

**Comment by AMiniLegend** [comment] 2018-07-19 13:32
What data are you trying to collect? I'm not sure what the tool has enabled, but I think you should be able to get guild member data, if you have the tool running and go to Clan->Clan->Members

**Comment by AMiniLegend** [comment] 2018-07-19 13:35
If you're building from the source, you'll have to un-comment the ".Packet(" lines you want from the HandlerInt.cs file, since all of the functions are disabled.

**Comment by patotskiy** [comment] 2018-07-19 13:50
@AMiniLegend Thanks a lot for your help! It's hard to understand C# when you write on java

**Comment by AMiniLegend** [comment] 2018-07-19 13:52
No problem, I hope you get it working.

**Comment by patotskiy** [comment] 2018-08-15 19:04
@AMiniLegend 
After latest release I faced with issue which was mentioned above: 
```
Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at L2RPacketReader.PacketReader.ReadString()
   at L2RPacketReader.Parser.Parsers.PktGuildMemberListReadresult.Packet(PacketReader packet)
   at L2RPacketReader.Parser.Handler.Parse(PacketReader packet, UInt16 packetID)
   at L2RPacketReader.RecordPackets.AppendIncomingData(Byte[] payloadData)
   at L2RPacketReader.RecordPackets.PacketCapturer(Object sender, CaptureEventArgs e)
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Could you please help me?

**Comment by Moxer81** [comment] 2018-09-21 02:07
I am having the same problem when trying to get GuildRankings list. I think there is a problem with the packet parser and I have zero knowledge of c#. If anyone can help fixing this I would really be thankful!

the main error is: Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes

**Closed as completed** 2018-10-29 05:04 UTC
